apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-postgresql-pv
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.global.postgresql.persistence.mountPath }}"
