- block:
    - import_role:
        name: post-metadata
        tasks_from: store
  vars:
    id: 1.1.2
    name: Corosync consensus is set to 36000
    labels: generic
    description: |
      Test if the configured corosync consensus has the correct value: 36000
    remediation: |
        ## Remediation
        Adjust the Corosync `consensus` timeout as recommended on the Azure best practices.

        ## References
        - https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker
    implementation: "{{ lookup('file', 'roles/1.1.2/tasks/check.yml') }}"
